# Generated by Django 2.0.1 on 2018-01-19 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=40)),
                ('categorydescription', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=40)),
                ('rating', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('productimg', models.CharField(max_length=40, null=True)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.Brand')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.Category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
