# Generated by Django 2.0.1 on 2018-01-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
